Repository codeit-FE18-part3/Thejulge, pull requests merged in 2025-10, with the labels that each got.

#17 ✨ feat: dropdown 구현 #11
  .eslintrc.js
  src/components/layout/container/container.tsx
  src/components/ui/dropdown/dropdown.stories.tsx
  src/components/ui/dropdown/dropdown.tsx
  src/components/ui/dropdown/index.ts
  src/components/ui/icon/Icon.stories.tsx
  src/components/ui/index.ts
  src/constants/dropdown.ts
  src/constants/icon.ts
  src/hooks/useClickOutside.tsx
  src/hooks/useToggle.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore

#22 [✨feat] 테이블 생성 #6
  src/components/ui/table/Table.stories.tsx
  src/components/ui/table/Table.tsx
  src/components/ui/table/TableRow.tsx
  src/components/ui/table/TableRowProps.tsx
  src/components/ui/table/index.tsx
  src/components/ui/table/testApi.tsx
  src/lib/utils/getTime.ts
Labels: ✨ feat

#26 ✨feat: 공통 컴포넌트 인풋 구현
  src/components/ui/input/input.stories.tsx
  src/components/ui/input/input.tsx
  src/components/ui/modal/modal.stories.tsx
  src/components/ui/modal/modal.tsx
Labels: ✨ feat

#32 [✨feat] 알림 모달 생성
  src/assets/icon/ic-result-badge.svg
  src/components/ui/index.ts
  src/components/ui/modal/index.ts
  src/components/ui/modal/notification/Notification.stories.tsx
  src/components/ui/modal/notification/Notification.tsx
  src/components/ui/modal/notification/NotificationMessage.tsx
  src/components/ui/modal/notification/ResultBadge.tsx
  src/components/ui/modal/notification/index.ts
  src/components/ui/table/Table.stories.tsx
  src/components/ui/table/Table.tsx
  src/components/ui/table/TableRow.tsx
  src/components/ui/table/testApi.tsx
  src/constants/icon.ts
  src/lib/utils/getTime.ts
  src/lib/utils/timeAgo.ts
  src/types/notice.ts
Labels: ✨ feat, ♻️ refactor, 🍱 asset

#33 ✨ Feat: 공통 컴포넌트 Pagination 설계
  src/components/layout/footer/footer.tsx
  src/components/layout/footer/index.ts
  src/components/layout/frame/index.ts
  src/components/layout/index.ts
  src/components/ui/pagination/index.ts
  src/components/ui/pagination/pagination.tsx
  src/context/appProvider.tsx
  src/context/toastContext/index.ts
  src/pages/_app.tsx
Labels: ✨ feat

#34 ✨feat: 모달 컴포넌트 개선 및 접근성 향상 & 경로수정
  src/components/ui/button/index.ts
  src/components/ui/index.ts
  src/components/ui/input/index.ts
  src/components/ui/modal/index.ts
  src/components/ui/modal/modal.tsx
  src/components/ui/modal/notification/index.ts
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#35 ✨feat: post 컴포넌트 작성
  next.config.mjs
  src/components/ui/icon/icon.tsx
  src/components/ui/index.ts
  src/components/ui/post/index.ts
  src/components/ui/post/mockData.json
  src/components/ui/post/post.stories.tsx
  src/components/ui/post/post.styles.ts
  src/components/ui/post/post.tsx
  src/components/ui/post/postWrapper.tsx
  src/constants/icon.ts
  src/lib/utils/calcPayIncrease.ts
  src/lib/utils/cn.ts
  src/lib/utils/formatNumber.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/types/notice.ts
  src/types/shop.ts
Labels: ✨ feat, 🐛 fix

#39 ✨ feat: dropdown 컴포넌트 리팩토링 및 기존 기능 개선 #36
  src/components/ui/dropdown/dropdown.stories.tsx
  src/components/ui/dropdown/dropdown.styles.ts
  src/components/ui/dropdown/dropdown.tsx
  src/components/ui/dropdown/hooks/useDropdown.ts
  src/components/ui/dropdown/hooks/useDropdownPosition.ts
  src/components/ui/dropdown/hooks/useDropdownScroll.ts
  src/components/ui/dropdown/hooks/useKeyboardNavigation.ts
  src/hooks/useAuth.ts
  src/hooks/useClickOutside.ts
  src/hooks/useEscapeKey.ts
  src/hooks/useSafeRef.ts
  src/hooks/useToggle.ts
  src/lib/utils/cn.ts
Labels: ✨ feat, ♻️ refactor, 🔧 chore, 🌟 enhancement
